- .github/workflows/ci-cd.yml
- pom.xml
> hotfix: 애플리케이션 이름 업데이트 및 CI/CD 워크플로우 수정

- pom.xml
- src/main/resources/application.yml
- hotfix: 롬복 빌드 에러 수정
어떤 변경 사항이 있나요?
> hotfix: 롬복 빌드 에러 수정

- src/main/java/com/nhnacademy/front/common/filter/AuthRequiredFilter.java
- src/main/java/com/nhnacademy/front/shop/controller/UserController.java
- feat: 액세스 토큰 만료기간 체크 로직 수정
어떤 변경 사항이 있나요?
> feat: 액세스 토큰 만료기간 체크 로직 수정

- src/main/resources/templates/book/book-detail.html
- src/main/resources/templates/user/me-reviews.html
- 리뷰 이미지 관련 오류 수정
어떤 변경 사항이 있나요?
> hotfix: 리뷰 이미지 오류 수정

- src/main/java/com/nhnacademy/front/admin/controller/AdminOrderController.java
- src/main/java/com/nhnacademy/front/admin/order/AdminOrderClient.java
- src/main/java/com/nhnacademy/front/admin/order/AdminOrderService.java
- src/main/java/com/nhnacademy/front/shop/order/dto/RefundResponse.java
- src/main/resources/templates/admin/order/refund.html
> hotfix: 관리자 반품 시 userID 미반영 문제 해결

- src/main/java/com/nhnacademy/front/admin/controller/AdminUserManagementController.java
- src/main/java/com/nhnacademy/front/shop/membership/service/MembershipService.java
- src/main/resources/static/css/output.css
- src/main/resources/templates/admin/user/membership-management.html
- src/main/resources/templates/auth/login.html
- 맴버십 활성화 토글 버튼 수정
어떤 변경 사항이 있나요?
> feat: 맴버십 활성화 토글 버튼 수정

- src/main/java/com/nhnacademy/front/admin/controller/AdminUserManagementController.java
- src/main/java/com/nhnacademy/front/shop/membership/dto/MembershipUpdateFormRequest.java
- src/main/resources/templates/admin/user/membership-management.html
- 맴버십 활성화/비활성화 오류 수정
어떤 변경 사항이 있나요?
> hotfix: 맴버십 활성화/비활성화 오류 수정

- src/main/java/com/nhnacademy/front/auth/client/dto/LoginRequest.java
- src/main/java/com/nhnacademy/front/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/front/auth/dto/ClientLoginRequest.java
- src/main/java/com/nhnacademy/front/auth/service/AuthService.java
- src/main/java/com/nhnacademy/front/common/dto/FlashMessageDto.java
- src/main/java/com/nhnacademy/front/common/security/JwtAuthenticationFilter.java
- src/main/java/com/nhnacademy/front/common/security/LoginAuthenticationFilter.java
- src/main/java/com/nhnacademy/front/common/security/LoginFailureHandler.java
- src/main/java/com/nhnacademy/front/common/security/SecurityConfig.java
- src/main/java/com/nhnacademy/front/shop/controller/MyPageController.java
- src/main/java/com/nhnacademy/front/util/CookieUtil.java
- src/main/resources/static/css/output.css
- src/main/resources/templates/admin/user/membership-management.html
- src/main/resources/templates/auth/login.html
- src/main/resources/templates/auth/reactivate.html
- src/main/resources/templates/auth/register.html
- 로그인 유지 및 휴면 해제 기능 추가
어떤 변경 사항이 있나요?
> feat: 로그인 유지 및 휴면 해제 기능 추가

- src/main/resources/templates/auth/reactivate.html
- 코드 전송 요청의 바디 수정
어떤 변경 사항이 있나요?
> hotfix: 코드 전송 요청의 바디 수정

- src/main/resources/templates/auth/reactivate.html
- 휴면 해제 시 리디렉션 url 수정
어떤 변경 사항이 있나요?
> hotfix: 휴면 해제 시 리디렉션 url 수정

- src/main/java/com/nhnacademy/front/shop/book/dto/MainBookResponse.java
- src/main/java/com/nhnacademy/front/shop/cart/client/CartClient.java
- src/main/java/com/nhnacademy/front/shop/cart/dto/CartBookResponse.java
- src/main/java/com/nhnacademy/front/shop/cart/dto/CartCouponResponse.java
- src/main/java/com/nhnacademy/front/shop/controller/CartController.java
- src/main/java/com/nhnacademy/front/shop/controller/OrderController.java
- src/main/java/com/nhnacademy/front/shop/controller/OrderFromController.java
- src/main/java/com/nhnacademy/front/shop/couponStore/client/dto/CouponStoreDto.java
- src/main/java/com/nhnacademy/front/shop/couponStore/client/dto/DiscountType.java
- src/main/java/com/nhnacademy/front/shop/guest/service/GuestOrderService.java
- src/main/java/com/nhnacademy/front/shop/order/dto/OrderResponse.java
- src/main/resources/static/css/output.css
- src/main/resources/templates/auth/reactivate.html
- src/main/resources/templates/order/order-details.html
- src/main/resources/templates/order/order-form-guest-books.html
- src/main/resources/templates/order/order-form-user-books.html
- 주문서 페이지 보완
- 포인트와 할인금액 사이 영향주는 경우 사용자가 인식할 수 있게 javascript로 화면에 표시해줌
- 쿠폰 적용
- 쿠폰 적용은 1개만 가능하기 때문에 선택 시 다른 쿠폰 적용 불가하도록 적용
- 포장지 유무 기능 추가
어떤 변경 사항이 있나요?
> feat: 주문서 페이지 보완 및 쿠폰 적용, 포장지 유무 기능 추가

- src/main/java/com/nhnacademy/front/shop/book/dto/AladinBookResponse.java
- src/main/java/com/nhnacademy/front/shop/book/dto/BookCreateRequest.java
- src/main/java/com/nhnacademy/front/shop/book/dto/BookRegisterRequest.java
- src/main/java/com/nhnacademy/front/shop/book/dto/BookUpdateRequest.java
- src/main/resources/templates/admin/book/book-edit.html
도서 수정 시 기존 이미지가 보이지 않는 현상 수정
validation을 위해 기본형 > 참조형
어떤 변경 사항이 있나요?
> hotfix: 도서 수정 시 기존 이미지가 보이지 않는 현상 수정

- src/main/java/com/nhnacademy/front/admin/controller/AdminOrderController.java
- src/main/java/com/nhnacademy/front/admin/order/AdminOrderClient.java
- src/main/java/com/nhnacademy/front/admin/order/AdminOrderService.java
- src/main/resources/templates/admin/order/refund.html
- src/main/resources/templates/order/order-form-user-books.html
> hotfix: 재고 부족 에러 해결

- src/main/resources/static/css/output.css
- src/main/resources/templates/book/book-detail.html
- 찜 카운트 새로고침하지 않아도 바로 업데이트 되도록 수정
- 찜 유지 안되는 버그 수정
어떤 변경 사항이 있나요?
> hotfix: 찜 버튼 버그 수정 및 도서 상세 UI 수정

- src/main/java/com/nhnacademy/front/shop/cart/dto/CartCouponResponse.java
- src/main/java/com/nhnacademy/front/shop/controller/MyPageController.java
- src/main/java/com/nhnacademy/front/shop/controller/OrderFromController.java
- src/main/java/com/nhnacademy/front/shop/couponStore/client/CouponStoreClient.java
- src/main/java/com/nhnacademy/front/shop/couponStore/dto/CouponStatus.java
- src/main/java/com/nhnacademy/front/shop/couponStore/dto/CouponStoreDto.java
- src/main/java/com/nhnacademy/front/shop/couponStore/dto/CouponStoreResponse.java
- src/main/java/com/nhnacademy/front/shop/couponStore/dto/DiscountType.java
- src/main/java/com/nhnacademy/front/shop/couponStore/dto/OriginType.java
- src/main/java/com/nhnacademy/front/shop/couponStore/service/CouponStoreService.java
- src/main/resources/static/css/output.css
- src/main/resources/templates/user/me-coupons.html
> hotfix: 쿠폰함 조회 수정

- src/main/java/com/nhnacademy/front/shop/controller/GuestOrderController.java
- src/main/java/com/nhnacademy/front/shop/controller/PaymentController.java
- src/main/java/com/nhnacademy/front/shop/payment/client/PaymentClient.java
- src/main/java/com/nhnacademy/front/shop/payment/dto/PaymentCancelRequest.java
- src/main/java/com/nhnacademy/front/shop/payment/dto/PaymentResponse.java
- src/main/java/com/nhnacademy/front/shop/payment/service/PaymentService.java
- src/main/resources/templates/order/order-details.html
> feat: 결제 취소 시 토스 결체 취소 요청

- src/main/java/com/nhnacademy/front/shop/controller/BookController.java
- src/main/java/com/nhnacademy/front/shop/coupon/coupon/controller/CouponController.java
- src/main/resources/templates/admin/coupon/coupons.html
- src/main/resources/templates/admin/coupon/policies.html
> feat: coupon 수정

- src/main/resources/templates/admin/book/categories.html
- src/main/resources/templates/book/book-detail.html
- 도서 상세 페이지 불필요한 코드 삭제
어떤 변경 사항이 있나요?
> hotfix: 도서 상세 페이지 불필요한 코드 삭제

- src/main/java/com/nhnacademy/front/shop/point/policy/client/dto/PointPolicyCreateRequest.java
- src/main/java/com/nhnacademy/front/shop/point/policy/client/dto/PointPolicyUpdateRequest.java
- src/main/java/com/nhnacademy/front/shop/point/policy/dto/PointPolicyUpdateFormRequest.java
- src/main/java/com/nhnacademy/front/shop/point/policy/service/PointPolicyService.java
- src/main/resources/static/css/output.css
- src/main/resources/templates/admin/user/point-policy-management.html
- 포인트 정책 등록/수정 이미지 리뷰 포인트 연결 -> 3번 데이터 참고
어떤 변경 사항이 있나요?
> hotfix: 포인트 정책 등록/수정 이미지 리뷰 포인트 연결

- src/main/resources/templates/user/me-coupons.html
- 정량 할인 안 보이는 오류 해결
어떤 변경 사항이 있나요?
> hotfix: 정량 할인 안 보이는 오류 해결

- src/main/java/com/nhnacademy/front/shop/cart/client/CartClient.java
- src/main/java/com/nhnacademy/front/shop/controller/OrderFromController.java
- src/main/resources/static/css/output.css
- src/main/resources/templates/book/book-detail.html
- src/main/resources/templates/cart/carts.html
- 재고 부족할 경우 장바구니에 안 담기도록 수정
- 장바구니에서 선택된 상품만 주문하도록 수정
어떤 변경 사항이 있나요?
> hotfix: 장바구니에서 선택된 상품만 주문하도록 수정

- src/main/resources/templates/user/me-orders.html
- fetch 오류 원인이 될만한 로직 수정
어떤 변경 사항이 있나요?
> hotfix: 리뷰 등록 시 fetch 오류 원인이 될만한 로직 수정

- src/main/resources/templates/layout/fragments/nav.html
> hotfix: 카테고리 오류 수정

- src/main/java/com/nhnacademy/front/shop/controller/BookController.java
- src/main/resources/templates/book/book-detail.html
- 관리자일 경우에도 도서 상세페이지 보이도록 수정
어떤 변경 사항이 있나요?
> hotfix: 관리자일 경우에도 도서 상세페이지 보이도록 수정

- src/main/resources/templates/book/book-detail.html
- src/main/resources/templates/user/me-orders.html
- 도서 상세 조회 시 dev 붙도록 수정
- 리뷰 등록 시 redirect 수정
어떤 변경 사항이 있나요?
> hotfix: 도서 상세 조회 시 dev 붙도록 수정 및 리뷰 등록 시 redirect 수정

- src/main/resources/templates/user/me-orders.html
> hotfix: 리뷰 등록 오류 해결
